### ISSUE TITLE
JVM based version?

### ISSUE THREAD

**Issue by Sciss** [CalumJEadie/video-processing-language-for-the-raspberry-pi#1]
Hi,

sorry if this is not suitable for 'GitHub Issues', it was just the fastest way for me to get in touch.
I skimmed through your thesis, and noticed that you describe at some point using JogAmp to decode mp4/h264 video frames, supposedly on the JVM. You mention a `MovieCube` example. I have not found any references to this on the Internet, so I would be extremely grateful if you could point me to any resources that should how to efficiently decode a video on the Raspberry Pi using a JVM library or Java bindings. Thanks!

**Comment by CalumJEadie** [comment]
Hi Sciss,

I remember in the early stages of the project I was exploring what was possible on the Pi at the time and used MovieCube as one of the test applications.

If you search for "JogAmp MovieCube" you should find the JogAmp docs and code. Including:
- https://github.com/sgothel/jogl/blob/master/src/test/com/jogamp/opengl/test/junit/jogl/demos/es2/av/MovieCube.java

There's also some research code I have on GitHub that might be helpful to you:
- https://github.com/CalumJEadie/part-ii-individual-project-dev/tree/master/research/JogAmp%20-%20Rendering%20video%20to%20surface
- https://github.com/CalumJEadie/part-ii-individual-project-dev/blob/master/research/JogAmp%20-%20Rendering%20video%20to%20surface/run-movie-simple-youtube.sh
- https://github.com/CalumJEadie/part-ii-individual-project-dev/blob/master/research/performance-evaluation-tools/youtube-movie-cube-experiment.py
- https://github.com/CalumJEadie/part-ii-individual-project-dev/blob/master/research/performance-evaluation-tools/youtube-omxplayer-experiment.py

Hope that helps!

**Comment by Sciss** [comment]
Thanks, that's very helpful!
